### ISSUE TITLE
Harrogate takes a super long time to load harrogate-index-app.js, driver issues, and other problems

### ISSUE THREAD

**Issue by Zacharyprime** [kipr/harrogate#103]
![harrogate performance](https://user-images.githubusercontent.com/24783598/122947464-cb2c2380-d33f-11eb-8f47-d498cb1c022a.png)

This is a consistent result for me, on different Wombats. Sometimes it just appears to not load at all, but that could be that the connection is at the limits of my patience.

This might just be an issue with the page loading time in general, the specific file may not be important.
The core of the issue is that harrogate takes WAY to long to load, at least on the Wombat.

**Comment by Zacharyprime** [comment]
The resulting file is just a load of scripts pieced together and used as one file. I don't know enough about coffee script to know if this is normal behavior

**Comment by Zacharyprime** [comment]
I tried pulling https://github.com/kipr/harrogate/commit/8c4f142f23be696326c7a869ef0310c67c009767 and running it.
The same issue occurs, which leads me to believe that the network is setup incorrectly or that there is some standard that has been implemented or bumped and is causing problems between this ancient software and modern browsers.

**Comment by Zacharyprime** [comment]
I tried moving:
```js
harrogate_app.use(Express["static"](__dirname + '/public'));
```

from the middle to the top (right after the authentication step), but the timing seemed to be unaffected.

**Comment by Zacharyprime** [comment]
In the branch "test" (which may or may not be deleted by the time someone reads this), I tried removing the passport password authentication code from [server.js](https://github.com/kipr/harrogate/blob/master/server.js) (lines 76 - 128).

This resulted in a pretty massive speed boost loading time of ~1 minute.
I don't think this is the root cause of the performance issue, I think this is a bandaid solution that might cut the speed down a little.

I am not sure why that part of the code is even there, I can't think of a reason for harrogate to have authentication other than the Pi stacks that run the IDE.

**Comment by Zacharyprime** [comment]
This was discussed extensively on discord.

Braden recommended using a perf flame chart and the results of that were odd.
It is likely that the SD card image has damaged sectors and that may be the cause of this issue.

I am going to try building an image from scratch using the qt4 branch of libkar and hopefully that will solve this.

**Comment by Zacharyprime** [comment]
I used badblocks to test for bad sectors, but it came back with no issues.
I checked for thrashing but the swap space wasn't even being used.
I tried adjusting the heap size limit both up and down, but that didn't have any perceivable change in performance.
I tried updating npm, which just caused more warnings to be thrown with no boost in performance.
running npm, gulp, and node without sudo did not boost performance (but is how those should be ran in the future)

**Comment by Zacharyprime** [comment]
I suspected that this is a problem with the wifi setup, so I tested an ethernet connection and a wifi connection and got these results:
Ethernet: 550 ms
![ethernettest](https://user-images.githubusercontent.com/24783598/131863484-c73f38bd-3331-4505-b2f2-daf8bbba1323.png)

Wifi: 49.32 s
![wifitest](https://user-images.githubusercontent.com/24783598/131863536-c4883cd5-d288-4cb4-8ae0-1fdaaceeb7ea.png)

This means that the issue is with the transfer rate of the wifi, or the wifi setup in general. The wifi has been pretty jank anyway, hopefully if we fix this the other issues will resolve with it.

**Comment by Zacharyprime** [comment]
From searching online, using the pi as an access point like this seems to be the source of the problem. The throughput of the Pi's wifi card is simply not high enough because it wasn't designed to be a dedicated AP.

wmm_enable is set to 1 as it should be, so it's not a QoS issue.

I also checked the rest of the hostapd config along with the changes that wifi_configurator.py applies, and I don't see anything that could be modified to boost speed.

**Comment by Zacharyprime** [comment]
When trying to update to stretch, the SD card fills up at like 60% (I'm not sure exactly where, I just know it wasn't very far into the install process). I need to find a larger SD card to do the update on, and then try to trim even more until it will fit into 8gb. If I can't trim it and this somehow ends up being a solution, we would have to upgrade to a 16gb SD card instead.

**Comment by Zacharyprime** [comment]
The Pi3B uses the Cypress CYW43438 chip, and 802.11n 2.4GHz wireless chip, which is the same configuration used on the Pi Zero W

**Comment by Zacharyprime** [comment]
Possible solution:
https://forums.freebsd.org/threads/raspberry-3b-and-slow-wifi-speed.72877/

**Comment by Zacharyprime** [comment]
Updating to stretch just caused all of the issues that happen with a fresh image of raspberry pi OS.

**Comment by Zacharyprime** [comment]
Updating to the latest version of the rpi kernel (5.10 as of writing this), causes all of the issues with using a fresh image. This means that it is the kernel that is the root cause of the problems (other than the main wifi issue we are trying to solve)

**Comment by Zacharyprime** [comment]
These are the loaded kernel modules:
binfmt_misc 6236 1 - Live 0x7f3f0000
joydev 9024 0 - Live 0x7f3e9000
tsc_raspi 1194 0 - Live 0x7f3e5000 (O)
tsc2007 4639 0 - Live 0x7f3e0000 (O)
brcmfmac 177635 0 - Live 0x7f397000
brcmutil 5501 1 brcmfmac, Live 0x7f35e000
evdev 10278 5 - Live 0x7f357000
cfg80211 407580 1 brcmfmac, Live 0x7f296000
rfkill 16036 2 cfg80211, Live 0x7f21f000
snd_soc_bcm2708_i2s 6670 2 - Live 0x7f21a000
snd_soc_hifiberry_dac 2367 0 - Live 0x7f216000
snd_soc_pcm5102a 1635 1 - Live 0x7f212000
regmap_mmio 2842 1 snd_soc_bcm2708_i2s, Live 0x7f20e000
snd_soc_core 128477 3 snd_soc_bcm2708_i2s,snd_soc_hifiberry_dac,snd_soc_pcm5102a, Live 0x7f172000
snd_compress 7689 1 snd_soc_core, Live 0x7f160000
snd_pcm_dmaengine 3231 1 snd_soc_core, Live 0x7f151000
i2c_bcm2708 4920 0 - Live 0x7f14c000
bcm2835_gpiomem 2860 0 - Live 0x7f148000
bcm2835_rng 1763 0 - Live 0x7f144000
snd_pcm 73474 3 snd_soc_hifiberry_dac,snd_soc_core,snd_pcm_dmaengine, Live 0x7f11b000
spi_bcm2835 7074 0 - Live 0x7f103000
snd_timer 18848 1 snd_pcm, Live 0x7f0ef000
snd 50779 4 snd_soc_core,snd_compress,snd_pcm,snd_timer, Live 0x7f0c1000
uio_pdrv_genirq 2944 0 - Live 0x7f0ad000
uio 7753 1 uio_pdrv_genirq, Live 0x7f08f000
i2c_dev 5671 0 - Live 0x7f08a000
fuse 80694 3 - Live 0x7f06d000
ipv6 338660 51 [permanent], Live 0x7f000000

The tsc_raspi can be found [here](https://github.com/dhruvvyas90/TSC2007-Rpi-driver), however I have tried to install this in the past to a fresh image and it did not work.

**Comment by Zacharyprime** [comment]
**To summarize:**
I think that Josh/Mustafa/Raj used the program linked above as the drivers for the Wombat. Those are not official drivers from Texas Instruments, but custom drivers that that particular user made specifically for the raspberry pi. The driver was also written for the raspi kernel 3.x.x and earlier, but the current kernel is version 5.x.x.

This chip is not really used by anyone anymore from what I can find, even Texas Instrument's documentation is pretty sparse. Nearly every person online that I've found using a touchscreen with a modern pi is using the [7" display](https://www.amazon.com/Raspberry-Pi-7-Touchscreen-Display/dp/B0153R2A9I) that is designed to be plug and play with the Pi.

To get this driver functional to modern linux/raspbian, we would have to write our own drivers to interact with the new versions of raspi kernel, which would likely require a deep understanding of how the kernel works, while I only have a rough big picture understanding of it.

In addition, this is all a side quest towards solving the main problem of the WiFi transfer rate being far too low (at least when serving node pages). I cannot find a problem with our configuration, so it's mainly just a hunch that the WiFi speed is tied to how outdated the software is.

 It's also because getting updated to stretch or higher is going to become a bigger and bigger problem. Jessie is still in extended LTS right now as an archived release (actually according to debian ELTS rules, it expired on June 30th). As the software becomes further into the obsolete, packages that we use as dependencies will one by one start losing support (we won't be able to install them with apt anymore) and source links will start to go dead. 

For more information:
[Debian Releases](https://www.debian.org/releases/)
[Debian LTS Schedule](https://wiki.debian.org/LTS)

**Comment by bmcdorman** [comment]
I have experience writing kernel drivers on linux and Windows. Happy to be a reference or lead the effort, time permitting.

**Comment by Zacharyprime** [comment]
The driver is for the Pi to interact with a TSC2007 touchscreen controller chip.
The driver needs to read in the output from that chip and then apply the mouse position to that reported value and register clicks;
[TSC2007 Texas Instruments](https://www.ti.com/product/TSC2007)
[Texas instruments driver guide](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwje-rGM0IPzAhWnnGoFHQJPA4cQFnoECAQQAQ&url=https%3A%2F%2Fwww.ti.com%2Flit%2Fpdf%2Fsbaa170&usg=AOvVaw3ErHfFfKqyVGjCalm2qt4M)

**Comment by Zacharyprime** [comment]
Leaving this as a note for lab staff:
These are people who have requested we contact them when we fix this issue:
(917) 449 - 5755

**Comment by EugeneDMyers** [comment]
I faced some similer WiFi performance issues when working on the tello support, try installing this package:

rng-tools    

it provides better random number seeds, apparently w/o it , in high traffic situations the interface intentionally slows down because of some security issue
