### ISSUE TITLE
Splitting projects in lib and src folders makes it hard to use version control

### ISSUE THREAD

**Issue by snoato** [kipr/harrogate#25]
Having the files of a project separated in two directories which are shared with other projects (src and lib)  with a directory for the project in each one of those (e.g. src/projectName and lib/projectName) as it is in the testing version 1.1.5 makes it hard to use version control systems like Git for a single project or even maintaining multiple repos for multiple projects. It would be awesome if this is changed in a future release.

**Comment by jsoutherland** [comment]
Thanks @snoato we finally fixed this in #46
