### ISSUE TITLE
Structure of users.json

### ISSUE THREAD

**Issue by PhilipTrauner** [kipr/harrogate#3]
Please provide the structure of users.json in the readme file or remove it from the .gitignore.

**Comment by zeltner** [comment]
Hi! user.json should get generated and managed by scripts/user-manager.coffee. So I am not sure if it is useful in the readme. It contains serialized instances of the User class (scripts/user.coffee). 
For example:
```
{
  "stefan": {
    "login": "stefan",
    "preferences": {
      "workspace": {
        "path": "C:\\Users\\stefan\\Documents\\KISS"
      }
    }
  }
}
```

Its purpose is to store user preferences in a persistent way.

**Comment by PhilipTrauner** [comment]
Thanks for the quick answer!

**Comment by zeltner** [comment]
No problem. I'm happy that somebody is testing harrogate. Keep us posted if
you find more bugs or have suggestions.
Note that harrogate is not released yet so don't expect everything to work
:). If you would like to compile a program, please remove the line -laurora
from apps/compiler/compilation-environments/c/gcc.coffee as aurora is not
online available yet.
Thanks!!
